version: 2
jobs:
  build:
    docker:
      - image: archlinux/base
    steps:
      - checkout
      - run:
          name: Install
          command: pacman -Sy fish git curl openssh base-devel --noconfirm --noconfirm
      - add_ssh_keys:
          fingerprints:
            - "80:3e:3f:f6:27:dc:90:db:55:6f:f9:c5:20:ad:99:fd"
      - run:
          name: Build
          command: ./build.sh
      - store_artifacts:
          path: dist/_repo