version: 2
jobs:
  build:
    docker:
      - image: base/devel
    steps:
      - checkout
      - run:
          name: Install
          command: pacman -Syu fish git curl openssh --noconfirm
      - run:
          name: Build
          command: ./build.fish
