version: 2
jobs:
  build:
    docker:
      - image: base/devel
    steps:
      - checkout
      - run:
          name: Install
          command: pacman -Syu fish git curl openssh --noconfirm
      - add_ssh_keys:
          fingerprints:
            - "80:3e:3f:f6:27:dc:90:db:55:6f:f9:c5:20:ad:99:fd"
      - run:
          name: Build
          command: ./build.fish
      - store_artifacts:
          path: dist/_repo